version: "3"
services:
  ws-server:
    build:
      context: .
      dockerfile: ./docker/ws-server/Dockerfile
    ports:
      - "5001:5001"
    volumes:
     - ./ws-public/:/var/www/ws-server/
  page-server:
    build:
      context: ./
      dockerfile: ./docker/page-server/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./page-public/:/usr/local/apache2/htdocs/